### ISSUE TITLE
Add a demo page

### ISSUE THREAD

**Issue by Gpx** [viamarte/modernweb#2]
It would be good to have a demo page link in the README file.

**Comment by mrjoelkemp** [comment]
+1

**Comment by mkxml** [comment]
Thanks for the tip @Gpx. Nice, I will do that soon.

**Comment by Gpx** [comment]
@mkautzmann thank you, I'm looking forward.

**Comment by i8ramin** [comment]
+1

**Comment by trailsandtribulations** [comment]
+1.  also, saying which browsers/versions pass/fail would be good info

**Comment by MDonnellyDev** [comment]
A demo page would certainly be nice.  You could also simply add one or two images to the Readme.md as a quick example.

**Comment by mkxml** [comment]
I'm already working on a demo website, it should be up later today or tomorrow. But @MDonnellyDev suggestion is good, I will add sample images on README.md as well.

**Comment by Gpx** [comment]
:+1:

**Comment by mkxml** [comment]
OK guys, the website is up and one sample banner image is on the README file. So I'm closing this issue. If you notice anything out of context please let me know. Thank you :)
