### ISSUE TITLE
Use long links instead of bit.ly

### ISSUE THREAD

**Issue by Gpx** [viamarte/modernweb#3]
The links to Opera and to upgrade IE are minified. I think the user would prefer to see what he's clicking. Also the redirect would be faster. Since the url is not displayed in the page there's no use for a "bit.ly version".

**Comment by mkxml** [comment]
I understand your point, but I chose to use short URLs on Opera and IE for one reason only: HTTPS supports. I couldn't find HTTPS capable download links for these browsers so I had to use bit.ly to encapsulate them.

Why is this necessary?

I don't want to break websites that use HTTPS, so the banner must have all external links in this protocol.

If you have another option besides shortening those two links please let me know.

**Comment by Gpx** [comment]
I need to think about that.
