### ISSUE TITLE
Fix download links

### ISSUE THREAD

**Issue by Gpx** [viamarte/modernweb#9]
Links to Chrome, Firefox and Safari lead to a Portuguese version. I think it would be better to redirect to an "international" page or at least an English one.

**Comment by mkxml** [comment]
You are right, I am going to fix that. I'll close this issue when done. Thank you for reporting this @Gpx :)

**Comment by Gpx** [comment]
Those are the links I suggest:
- Chrome https://google.com/chrome
- Firefox https://mozilla.com/firefox
- Safari https://www.apple.com/safari

**Comment by mkxml** [comment]
I think it's solved now. Thanks again @Gpx!

**Comment by Gpx** [comment]
Thanks for that :+1:
